name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'School/package-lock.json'

      - name: Install dependencies
        working-directory: ./School
        run: npm ci

      - name: Run ESLint
        working-directory: ./School
        run: npm run lint

      - name: Run TypeScript check
        working-directory: ./School
        run: npm run type-check

      - name: Build production
        working-directory: ./School
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: production-build
          path: School/dist/
          retention-days: 30

  create-release:
    needs: lint-and-test
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: production-build
          path: dist/

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: OpenEdTex ${{ github.ref }}
          body_path: School/RELEASE_NOTES.md
          draft: false
          prerelease: false

      - name: Archive production build
        run: |
          cd dist
          zip -r ../openedtex-${{ github.ref_name }}-production.zip .
          cd ..

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./openedtex-${{ github.ref_name }}-production.zip
          asset_name: openedtex-${{ github.ref_name }}-production.zip
          asset_content_type: application/zip