# Generated by Django 4.2.7 on 2025-09-01 03:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0001_initial"),
        ("ai_assistant", "0001_initial"),
        ("classrooms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("total_users", models.PositiveIntegerField(default=0)),
                ("active_users", models.PositiveIntegerField(default=0)),
                ("new_users", models.PositiveIntegerField(default=0)),
                ("total_courses", models.PositiveIntegerField(default=0)),
                ("total_lessons", models.PositiveIntegerField(default=0)),
                ("total_enrollments", models.PositiveIntegerField(default=0)),
                ("total_sessions", models.PositiveIntegerField(default=0)),
                ("total_session_time", models.PositiveIntegerField(default=0)),
                ("total_page_views", models.PositiveIntegerField(default=0)),
                ("total_ai_interactions", models.PositiveIntegerField(default=0)),
                ("courses_completed", models.PositiveIntegerField(default=0)),
                ("lessons_completed", models.PositiveIntegerField(default=0)),
                ("quizzes_attempted", models.PositiveIntegerField(default=0)),
                (
                    "average_completion_rate",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("api_requests", models.PositiveIntegerField(default=0)),
                (
                    "error_rate",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=100, unique=True)),
                ("start_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("duration", models.PositiveIntegerField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("device_type", models.CharField(blank=True, max_length=50, null=True)),
                ("browser", models.CharField(blank=True, max_length=50, null=True)),
                ("os", models.CharField(blank=True, max_length=50, null=True)),
                ("page_views", models.PositiveIntegerField(default=0)),
                ("courses_viewed", models.PositiveIntegerField(default=0)),
                ("lessons_viewed", models.PositiveIntegerField(default=0)),
                ("quizzes_attempted", models.PositiveIntegerField(default=0)),
                ("ai_interactions", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="UserAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_sessions", models.PositiveIntegerField(default=0)),
                ("total_session_time", models.PositiveIntegerField(default=0)),
                ("average_session_duration", models.PositiveIntegerField(default=0)),
                ("courses_enrolled", models.PositiveIntegerField(default=0)),
                ("courses_completed", models.PositiveIntegerField(default=0)),
                ("lessons_completed", models.PositiveIntegerField(default=0)),
                ("quizzes_attempted", models.PositiveIntegerField(default=0)),
                (
                    "average_quiz_score",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("total_page_views", models.PositiveIntegerField(default=0)),
                ("total_ai_interactions", models.PositiveIntegerField(default=0)),
                ("total_study_time", models.PositiveIntegerField(default=0)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("last_activity", models.DateTimeField(blank=True, null=True)),
                ("streak_days", models.PositiveIntegerField(default=0)),
                ("preferred_subjects", models.JSONField(blank=True, default=list)),
                (
                    "preferred_difficulty",
                    models.CharField(default="intermediate", max_length=20),
                ),
                (
                    "learning_style",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-total_session_time"],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("user_activity", "User Activity Report"),
                            ("course_performance", "Course Performance Report"),
                            ("platform_overview", "Platform Overview Report"),
                            ("engagement_analysis", "Engagement Analysis Report"),
                            ("learning_outcomes", "Learning Outcomes Report"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("date_range_start", models.DateField()),
                ("date_range_end", models.DateField()),
                ("filters", models.JSONField(blank=True, default=dict)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("summary", models.TextField(blank=True, null=True)),
                ("is_generated", models.BooleanField(default=False)),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CourseAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_views", models.PositiveIntegerField(default=0)),
                ("unique_viewers", models.PositiveIntegerField(default=0)),
                ("total_enrollments", models.PositiveIntegerField(default=0)),
                ("active_enrollments", models.PositiveIntegerField(default=0)),
                (
                    "completion_rate",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "average_rating",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
                ),
                ("total_reviews", models.PositiveIntegerField(default=0)),
                ("average_session_duration", models.PositiveIntegerField(default=0)),
                ("total_study_time", models.PositiveIntegerField(default=0)),
                (
                    "average_progress",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("lessons_completed", models.PositiveIntegerField(default=0)),
                ("quizzes_attempted", models.PositiveIntegerField(default=0)),
                (
                    "average_quiz_score",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "ordering": ["-total_views"],
            },
        ),
        migrations.CreateModel(
            name="AnalyticsEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("login", "User Login"),
                            ("logout", "User Logout"),
                            ("page_view", "Page View"),
                            ("course_view", "Course View"),
                            ("lesson_view", "Lesson View"),
                            ("quiz_start", "Quiz Start"),
                            ("quiz_complete", "Quiz Complete"),
                            ("ai_chat", "AI Chat Interaction"),
                            ("classroom_join", "Classroom Join"),
                            ("classroom_leave", "Classroom Leave"),
                            ("enrollment", "Course Enrollment"),
                            ("completion", "Course Completion"),
                            ("download", "Resource Download"),
                            ("search", "Search Query"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("session_id", models.CharField(blank=True, max_length=100, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("duration", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "classroom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="classrooms.classroom",
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ai_assistant.aiconversation",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="courses.course",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="courses.lesson",
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ai_assistant.aiquiz",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "event_type"],
                        name="analytics_a_user_id_7df679_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="analytics_a_timesta_aef2a5_idx"
                    ),
                    models.Index(
                        fields=["event_type", "timestamp"],
                        name="analytics_a_event_t_64745b_idx",
                    ),
                ],
            },
        ),
    ]
