# Generated by Django 4.2.7 on 2025-09-01 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrandingConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "school_name",
                    models.CharField(
                        default="OpenEdTex University",
                        help_text="The name of the school/institution",
                        max_length=100,
                    ),
                ),
                (
                    "school_tagline",
                    models.CharField(
                        blank=True, help_text="School tagline or motto", max_length=200
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Main logo (PNG, JPG, SVG recommended)",
                        null=True,
                        upload_to="branding/logos/",
                    ),
                ),
                (
                    "logo_small",
                    models.ImageField(
                        blank=True,
                        help_text="Small logo for mobile/navbar",
                        null=True,
                        upload_to="branding/logos/",
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True,
                        help_text="Favicon (16x16, 32x32, ICO format)",
                        null=True,
                        upload_to="branding/favicons/",
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#007bff",
                        help_text="Primary brand color (hex code)",
                        max_length=7,
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        default="#6c757d",
                        help_text="Secondary brand color (hex code)",
                        max_length=7,
                    ),
                ),
                (
                    "accent_color",
                    models.CharField(
                        default="#28a745",
                        help_text="Accent/success color (hex code)",
                        max_length=7,
                    ),
                ),
                (
                    "background_color",
                    models.CharField(
                        default="#ffffff",
                        help_text="Background color (hex code)",
                        max_length=7,
                    ),
                ),
                (
                    "text_color",
                    models.CharField(
                        default="#212529",
                        help_text="Primary text color (hex code)",
                        max_length=7,
                    ),
                ),
                (
                    "primary_font",
                    models.CharField(
                        default="'Inter', sans-serif",
                        help_text="Primary font family",
                        max_length=50,
                    ),
                ),
                (
                    "heading_font",
                    models.CharField(
                        default="'Inter', sans-serif",
                        help_text="Heading font family",
                        max_length=50,
                    ),
                ),
                (
                    "support_email",
                    models.EmailField(
                        default="support@openedtex.edu",
                        help_text="Support contact email",
                        max_length=254,
                    ),
                ),
                (
                    "support_phone",
                    models.CharField(
                        blank=True, help_text="Support contact phone", max_length=20
                    ),
                ),
                (
                    "website_url",
                    models.URLField(
                        default="https://openedtex.edu", help_text="School website URL"
                    ),
                ),
                (
                    "facebook_url",
                    models.URLField(blank=True, help_text="Facebook page URL"),
                ),
                (
                    "twitter_url",
                    models.URLField(blank=True, help_text="Twitter/X profile URL"),
                ),
                (
                    "linkedin_url",
                    models.URLField(blank=True, help_text="LinkedIn page URL"),
                ),
                (
                    "instagram_url",
                    models.URLField(blank=True, help_text="Instagram profile URL"),
                ),
                (
                    "footer_text",
                    models.TextField(
                        default="© 2025 OpenEdTex University. All rights reserved.",
                        help_text="Footer copyright text",
                    ),
                ),
                (
                    "custom_css",
                    models.TextField(
                        blank=True, help_text="Custom CSS for additional styling"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this branding configuration is active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Branding Configuration",
                "verbose_name_plural": "Branding Configurations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BrandingPreset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
                ("primary_color", models.CharField(default="#007bff", max_length=7)),
                ("secondary_color", models.CharField(default="#6c757d", max_length=7)),
                ("accent_color", models.CharField(default="#28a745", max_length=7)),
                ("background_color", models.CharField(default="#ffffff", max_length=7)),
                ("text_color", models.CharField(default="#212529", max_length=7)),
                (
                    "primary_font",
                    models.CharField(default="'Inter', sans-serif", max_length=50),
                ),
                (
                    "heading_font",
                    models.CharField(default="'Inter', sans-serif", max_length=50),
                ),
                ("is_default", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Branding Preset",
                "verbose_name_plural": "Branding Presets",
            },
        ),
    ]
