global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'alerts@openedtex.com'
  smtp_auth_username: 'your-email@gmail.com'
  smtp_auth_password: 'your-app-password'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'email'
  routes:
  - match:
      severity: critical
    receiver: 'email'

receivers:
- name: 'email'
  email_configs:
  - to: 'admin@openedtex.com'
    from: 'alerts@openedtex.com'
    smarthost: smtp.gmail.com:587
    auth_username: 'your-email@gmail.com'
    auth_password: 'your-app-password'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
